name = "Lucas McKay"
rol = "Web Dev/Full Stack Programmer/Creative Technologist"
email = "lucas@lucasmckay.xyz"
phone = "+1 (805) 352-2795"
location = "Santa Barbara, California, USA"
avatar = "./config/assets/avatars/avatar-1.png"
username = "shredthaGNAR" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199666.5651251294!2d-121.58334177520186!3d38.56165006739519!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x809ac672b28397f9%3A0x921f6aaa74197fdb!2sSacramento%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd"
presentation = """
I'm Creative Technologist that focues on building kickass effecive websites and other types of media. Excel at being the digital Frankenstin and bringing websitee brands back from the dead.

As a web developer, my role is to craft a website for you that seamlessly blends functionality with an intuitive user experience, all while ensuring aesthetic appeal. I focus on infusing a unique personal touch into your product, ensuring it not only stands out with its visual allure but also offers ease of navigation. My goal is to convey your brand’s message and ethos through innovative design, creating an engaging online presence that resonates with your audience.
"""
